# Generated by Django 5.2.7 on 2025-11-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "base_url",
                    models.URLField(
                        help_text="The base URL, e.g., 'https://vegamovies.talk'",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Include this site in searches"
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[("GET", "GET Parameter"), ("POST", "POST API")],
                        default="GET",
                        max_length=4,
                    ),
                ),
                (
                    "search_endpoint",
                    models.CharField(
                        help_text="The search path. Use %QUERY% as placeholder, e.g., '/?s=%QUERY%&layout=talk'",
                        max_length=255,
                    ),
                ),
                (
                    "post_payload_template",
                    models.TextField(
                        blank=True,
                        help_text="For POST type only. A JSON/form-data template with '%QUERY%' as placeholder.",
                        null=True,
                    ),
                ),
                (
                    "requires_playwright",
                    models.BooleanField(
                        default=False,
                        help_text="Check this if the site is protected by Cloudflare or requires JS rendering",
                    ),
                ),
                (
                    "result_container_selector",
                    models.CharField(
                        help_text="CSS selector for the parent container of a single result (e.g., 'article.post-item')",
                        max_length=255,
                    ),
                ),
                (
                    "result_title_selector",
                    models.CharField(
                        help_text="CSS selector for the title text (e.g., 'h2.title a')",
                        max_length=255,
                    ),
                ),
                (
                    "result_link_selector",
                    models.CharField(
                        help_text="CSS selector for the result's <a> tag (e.g., 'h2.title a')",
                        max_length=255,
                    ),
                ),
                (
                    "result_poster_selector",
                    models.CharField(
                        help_text="CSS selector for the <img> tag (e.g., 'img.post-image')",
                        max_length=255,
                    ),
                ),
                (
                    "result_poster_attribute",
                    models.CharField(
                        default="src",
                        help_text="The attribute holding the image URL (e.g., 'src', 'data-src')",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
